name: hdkey
description: "Dart library for Bitcoin hierarchical deterministic keys (BIP32)"
version: 0.0.1
repository: https://github.com/mahsumurebe/dart-hdkey

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bip32: ^2.0.0
  bs58check: ^1.0.2
  elliptic: ^0.3.5
  hex: ^0.2.0
  pointycastle: ^3.3.4

dev_dependencies:
  bip39: ^1.0.6
  test: ^1.18.2
